/*
    This CUSTOM DOCUMENT was not generated by default. It is used to
    edit html and body tags as Next JS pages skip these tag definitions
    in the surrounding document's markup.

    For this example the html tag is configured to lang='en'
*/

import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {


  render() {
    return (
      <Html lang='en'>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument